### ISSUE TITLE
Exception after exiting the play mode

### ISSUE THREAD

**Issue by sathyarajshetigar** [smkplus/CustomToolbar#20] opened 2020-12-02 07:50 UTC
ArgumentException: Scene file not found: ''.
UnityEditor.SceneManagement.EditorSceneManager.OpenScene (System.String scenePath, UnityEditor.SceneManagement.OpenSceneMode mode) (at <007193b7fa9c4ad1be5b26df6a654213>:0)
UnityEditor.SceneManagement.EditorSceneManager.OpenScene (System.String scenePath) (at <007193b7fa9c4ad1be5b26df6a654213>:0)
ToolbarStartFromFirstScene.LogPlayModeState (UnityEditor.PlayModeStateChange state) (at Library/PackageCache/com.smkplus.custom-toolbar@34d4c8580b/Editor/CustomToolbar/Scripts/ToolbarElements/ToolbarStartFromFirstScene.cs:40)
UnityEditor.EditorApplication.Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange state) (at <007193b7fa9c4ad1be5b26df6a654213>:0)

**Comment by sathyarajshetigar** [comment] 2020-12-02 07:53
Check if the last play mode state is >= 0

**Comment by sathyarajshetigar** [comment] 2020-12-02 07:54
if (state == PlayModeStateChange.EnteredEditMode && EditorPrefs.HasKey("LastActiveSceneToolbar") && EditorPrefs.GetInt("LastActiveSceneToolbar") >= 0) {

**Comment by Team-on** [comment] 2020-12-10 10:22
Can't reproduce. @sathyarajshetigar can you provide more detailed steps?

**Comment by Team-on** [comment] 2021-09-21 12:51
I think it was fixed in 953fd4af0a6cc3f1c4ff24b0e878f71f80873d0e
@smkplus Can you close that?

**Closed as completed** 2021-09-22 03:03 UTC
