### ISSUE TITLE
Doesn't work in 2021.

### ISSUE THREAD

**Issue by MartinCapousek** [smkplus/CustomToolbar#24] opened 2021-02-05 17:30 UTC
It draws GUI elements on toolbar but they don't properly react on mouse events... e.g. scene drown-down does nothing on click.

**Comment by Team-on** [comment] 2021-02-05 18:46
I think we will just wait untill it would fixed by [marijnz](github.com/marijnz/unity-toolbar-extender)).

UT broke toolbar almost every update since 2020.1, so I recommend downgrade back and firstly check is toolbar got updated before upgrading project

**Comment by inertiave** [comment] 2021-02-06 16:30
I guess most of exception when try to get method information by reflection will be fixed if filter dll with
`"UnityEditor.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null";`
 instead of 
`"UnityEditor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null";`.

not confirmed yet. just guess.

**Comment by L1247** [comment] 2021-10-04 11:35
Already fixed by [marijnz](https://github.com/marijnz/unity-toolbar-extender)

**Comment by liveasnotes** [comment] 2021-11-23 02:58
I found that the Tab key works.
So, we can access the buttons by hitting Tab AFTER clicking the tool bar space.

**Closed as completed** 2022-01-30 12:59 UTC
